# Documentations -
# - https://github.com/actions/cache
# - https://github.com/actions/cache/blob/main/examples.md#node---npm

name: Tests

on:
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/database"
      ENV: "TEST"

    steps:
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    
    - name: Install pnpm and Node.js
      uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      with:
        cache: true
        install: false
    
    - name: Get pnpm metadata cache directory
      id: pnpm-metadata-cache-dir
      run: echo "dir=$(pnpm cache)" >> ${GITHUB_OUTPUT}
    
    - name: Restore pnpm metadata cache directory
      uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
      with:
        path: ${{ steps.pnpm-metadata-cache-dir.outputs.dir }}
        key: pnpm-metadata-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
    
    - run: pnpm install --frozen-lockfile
    - run: pnpm check
    - run: pnpm generate
    - run: pnpm test
