name: Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/database"
      ENV: "TEST"

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v6.0.8
      with:
        version: latest
    
    - name: Install dependencies
      run: pnpm install
    
    - name: Prisma Generate
      run: pnpm generate
    
    - name: Run tests
      run: pnpm test
